name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: user-management-api-1760578071
  AZURE_FRONTEND_NAME: user-management-frontend-1760578071
  AZURE_RESOURCE_GROUP: user-management-rg
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '18.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Verify Checkout
      run: |
        echo "Verifying checkout..."
        ls -la
        echo "Git status:"
        git status
        echo "Git log (last 3 commits):"
        git log --oneline -3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: user-management-frontend/package-lock.json
    
    - name: Restore dependencies
      run: dotnet restore UserManagementAPI/UserManagementAPI.csproj
    
    - name: Build
      run: dotnet build UserManagementAPI/UserManagementAPI.csproj --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish UserManagementAPI/UserManagementAPI.csproj --configuration Release --output ./publish
    
    - name: Verify Repository Structure
      run: |
        echo "Checking repository structure..."
        ls -la
        echo "Checking if frontend directory exists..."
        test -d user-management-frontend && echo "Frontend directory found" || echo "Frontend directory NOT found"
        if [ -d "user-management-frontend" ]; then
          echo "Frontend directory contents:"
          ls -la user-management-frontend/
        fi
    
    - name: Install Frontend Dependencies
      working-directory: user-management-frontend
      run: |
        echo "Installing frontend dependencies..."
        npm ci
        echo "Dependencies installed successfully"
    
    - name: Verify Frontend Structure
      working-directory: user-management-frontend
      run: |
        echo "Checking frontend structure..."
        ls -la
        echo "Checking public directory..."
        ls -la public/
        echo "Checking if index.html exists..."
        test -f public/index.html && echo "index.html found" || echo "index.html NOT found"
    
    - name: Build Frontend
      working-directory: user-management-frontend
      run: |
        echo "Building frontend..."
        echo "API URL: $REACT_APP_API_URL"
        npm run build
        echo "Frontend build completed"
    
    - name: Upload Backend Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ./publish
    
    - name: Upload Frontend Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: user-management-frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download Backend Artifacts
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: ./publish
    
    - name: Download Frontend Artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: ./frontend-build
    
    - name: Login to Azure (JSON Creds)
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Backend to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./publish
    
    - name: Deploy Frontend to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_FRONTEND_NAME }}
        package: ./frontend-build
